### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DanElliottPalmer** [cnduk/wc-ads#1]
- [x] Ad macro template
- [x] JS - GPT
- [x] JS - Gallery interstitial
- [x] JS - Inread video
- [x] JS - Promoted/Native
- [x] JS - Responsive
- [x] JS - OpenX
- [x] JS - Rubicon
- [x] JS - Legacy
